Fix nbformat to 5.2.0 to cell None type
Upgrading nbformat, as nbformat==5.1.2 and 5.1.3 causes "AttributeError: 'NoneType' object has no attribute 'cells'" due to upgrading nbformat to v4 `nb = nbformat.v4.upgrade(nb)`